### PR TITLE
Fix/remove all instructions

### PR DESCRIPTION
**Pull request by moT01**
Remove all instructions.

Related to: https://github.com/freeCodeCamp/freeCodeCamp/issues/39720

Edit: We could probably wait on merging this until [the associated PR](https://github.com/freeCodeCamp/freeCodeCamp/pull/39953) hits production

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]

**Comment by Sky020** [comment]
@moT01 Tom, are we set on having the **freeCodeCamp** heading in the READMEs?

**Comment by moT01** [comment]
No, we are not set on that if we don't want to be. It really doesn't matter, I would just prefer to keep them consistent. I was actually leaning towards removing it - I noticed Kris [put this in one of his PR's](https://github.com/freeCodeCamp/boilerplate-project-urlshortener/pull/23/files#diff-04c6e90faac2675aa89e2176d2eec7d8R1) - so I was thinking to go with that.

**Comment by Sky020** [comment]
@moT01 Thanks for that. It sounds like both Randell and yourself are leaning more towards removing it. So, I will remove it on my PRs.

@SaintPeter Rex, this seems like a confirmation that only **1** line should be in the README.

**Comment by moT01** [comment]
I updated the issues, and my PR's as well @Sky020 - I also turned the links into an h1 to match Kris's

**Review by Sky020 — APPROVED** [review]
LGTM 👍

**Review by RandellDawson — APPROVED** [review]
LGTM.  We can merge this once the `learn` changes hit production.

**Comment by RandellDawson** [comment]
Merging this one as https://github.com/freeCodeCamp/freeCodeCamp/pull/39953's changes have now hit production.

**Comment by RandellDawson** [comment]
@moT01 Thank you for your contribution! 👍
We're happy to accept these changes, and look forward to future contributions. 🎉

**Pull request merged**
