### PR TITLE
add console.log print

### PR DESCRIPTION
**Pull request by bpiontek1980**

### CODE REVIEW

**Review by bpiontek1980 — COMMENTED** [review]
Adding console.log line in myApp.js

**Review by bpiontek1980 — COMMENTED** [review]
passed, no conflicts

**Review by bpiontek1980 — COMMENTED** [review]
passed

**Comment by gikf** [comment]
Hey @bpiontek1980

Looks like this PR was supposed to be made on your own fork, instead of the original boilerplate repository.

This is a standard message notifying you that we've reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
