### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by pjsharpe07**
Added author: Preston k-v pair

### CODE REVIEW

**Comment by imcodingideas** [comment]
@pjsharpe07 thanks for the Pull Request but why are your authoring the package.json?

**Comment by pjsharpe07** [comment]
@imcodingideas That was my fault. I thought this was a cloned version of this code. I was practicing making pull requests. Sorry!

**Comment by thecodingaviator** [comment]
@pjsharpe07 I don't understand the point of this PR. What are you even changing?
image

**Comment by huyenltnguyen** [comment]
Hi @username, thank you for opening this pull request.

This is a standard message notifying you that we’ve reviewed your pull request and have decided not to merge it. We would welcome future pull requests from you.

Thank you and happy coding.

**Pull request closed without merging**
